In [53]:
def np_info (a):
    print(type(a), a.shape, a.dtype)

In [2]:
import numpy as np
a=np.random.normal(50,0.5,(32,3,224,224))
np_info(a)
a

NameError: name 'np_info' is not defined

In [23]:
a=np.arange(1,100)
len(a),a[49],len(a[:50]), len(a[50:])
np_info(a)

TypeError: can only concatenate str (not "int") to str

In [22]:
a=np.random.random((10,10))
np_info(a)

TypeError: can only concatenate str (not "int") to str

In [26]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
def add_one(a):
    a=a+1
    print(id(a))

In [30]:
add_one(a)
print(id(a))

2456084590096
2456083088944


In [31]:
def add_one(a):
    a = a + np.array([100])
    print(id(a))

In [32]:
add_one(a)
print(id(a))

2456084589616
2456083088944


In [33]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
b=a
b[4]=100
a

array([  0,   1,   2,   3, 100,   5,   6,   7,   8,   9])

In [38]:
b=a.copy()
b[4]=2
a

array([  0,   1,   2,   3, 100,   5,   6,   7,   8,   9])

In [39]:
a

array([  0,   1,   2,   3, 100,   5,   6,   7,   8,   9])

In [40]:
b

array([0, 1, 2, 3, 2, 5, 6, 7, 8, 9])

In [41]:
id(a),id(b)

(2456084589712, 2456084641616)

In [42]:
x=np.array([1,2,3])

In [43]:
x

array([1, 2, 3])

In [44]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [45]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [47]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [52]:
a=np.random.random((2,3))
a

array([[0.27916217, 0.10486591, 0.18442659],
       [0.78906641, 0.49387033, 0.54090751]])

In [55]:
b=a.reshape((3,2))
print(b)
np_info(b)

[[0.27916217 0.10486591]
 [0.18442659 0.78906641]
 [0.49387033 0.54090751]]
<class 'numpy.ndarray'> (3, 2) float64


In [56]:
c=a.flatten()
np_info(c)
c

<class 'numpy.ndarray'> (6,) float64


array([0.27916217, 0.10486591, 0.18442659, 0.78906641, 0.49387033,
       0.54090751])

In [57]:
np_info(a)

<class 'numpy.ndarray'> (2, 3) float64


In [60]:
d=np.expand_dims(a, axis=0)
np_info(d)

<class 'numpy.ndarray'> (1, 2, 3) float64


In [61]:
d

array([[[0.27916217, 0.10486591, 0.18442659],
        [0.78906641, 0.49387033, 0.54090751]]])

In [63]:
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [69]:
z=[99,99,99]
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


In [74]:
grid= np.array([[1,2,3],
                [4,5,6]])

In [75]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [76]:
b=np.random.random((32,28,28))
b.shape

(32, 28, 28)

In [77]:
b[:,np.newaxis,:].shape

(32, 1, 28, 28)

In [78]:
np.expand_dims(b,axis=1).shape

(32, 1, 28, 28)

In [80]:
np.expand_dims(b,axis=3).shape

(32, 28, 28, 1)

In [81]:
'abc'+'def'

'abcdef'

In [97]:
x1=np.random.random((2,3))
x2=np.random.random((2,3))

x1

array([[0.44969625, 0.45278177, 0.8773401 ],
       [0.79685491, 0.24759894, 0.45730687]])

In [90]:
x1.shape, x2.shape

((2, 3), (2, 3))

In [100]:
x3=np.concatenate([x1,x2],axis=1)

In [101]:
x3

array([[0.44969625, 0.45278177, 0.8773401 , 0.71526866, 0.01153905,
        0.49682704],
       [0.79685491, 0.24759894, 0.45730687, 0.44106358, 0.98577128,
        0.72650755]])

In [102]:
x3.shape

(2, 6)

In [103]:
x=np.array([1,2,3])
grid=np.array([[9,8,7],
               [6,5,4]])

In [104]:
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [110]:
y=np.array([[99],
           [99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [111]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [115]:
big_array=np.random.randint(1,100,size=1000000)
big_array.shape

(1000000,)

In [117]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i]=1.0/values[i]
    return output

    values = np.random.randint(1,10,size=5)
    compute_reciprocals(values)

In [118]:
%timeit compute_reciprocals(big_array)

1.2 s ± 17.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [119]:
%timeit (1.0/big_array)

2.46 ms ± 306 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [130]:
class my_array:
    def __init__(self,n):
        self.data=n
       
    def __add__(self,other):
        return self.data+other.data

In [131]:
a=my_array(5)
b=my_array(3)

In [132]:
a+b

8

In [136]:
a=np.array([1,2,3])

In [137]:
a**3

array([ 1,  8, 27], dtype=int32)

In [164]:
a=np.random.random((32,1,28,28))
b=np.random.random((32,3,224,224))
np_info(a),np_info(b)

<class 'numpy.ndarray'> (32, 1, 28, 28) float64
<class 'numpy.ndarray'> (32, 3, 224, 224) float64


(None, None)

In [165]:
np.max(a,axis=2).shape

(32, 1, 28)

In [141]:
a.shape, b.shape

((32, 1, 28, 28), (32, 3, 224, 224))

In [147]:
np.sum(a)

12550.599252953414

In [145]:
np.max(a)

0.9999415394497767

In [148]:
np.sum(a, axis=0)

array([[[17.42923356, 14.77174973, 17.49974779, 16.40803647,
         16.49223533, 15.6333399 , 15.87630323, 18.01248195,
         13.81608863, 15.7290132 , 13.02696863, 15.48012869,
         16.38188771, 16.90413719, 14.96564681, 13.8437982 ,
         15.57302039, 13.74435114, 16.13815009, 11.9417583 ,
         14.24462454, 17.07958992, 16.56479548, 18.40742415,
         14.62521459, 15.3607553 , 15.66523243, 16.51396768],
        [15.48451744, 16.21860252, 16.73475524, 14.01977158,
         15.2318411 , 16.74083852, 19.33215009, 14.58482499,
         19.65992836, 16.69487268, 15.59710391, 16.1999005 ,
         16.94663876, 14.72449726, 13.22894553, 15.49473578,
         16.11710786, 15.67558408, 17.55490246, 16.62419698,
         17.51983468, 17.1769912 , 16.25739661, 17.83145028,
         14.21867775, 14.63727322, 19.21572113, 15.15231597],
        [14.59532626, 13.1798964 , 16.83131289, 16.53110953,
         16.59306856, 15.98273796, 18.40235393, 16.74757142,
         14.42269599, 

In [149]:
np.sum(a,axis=0).shape

(1, 28, 28)

In [150]:
np.sum(a,axis=0).shape

(1, 28, 28)

In [161]:
a=np.random.randint(1,2,(2,3))
b=np.random.random((2,3))
a

array([[1, 1, 1],
       [1, 1, 1]])

In [162]:
np.sum(a,axis=2).shape

AxisError: axis 2 is out of bounds for array of dimension 2

In [154]:
np.sum(a,axis=1)

array([3, 3])

AxisError: axis 2 is out of bounds for array of dimension 2

In [156]:
np.random.randint(1,2)

1

AxisError: axis 2 is out of bounds for array of dimension 2

In [166]:
a=np.random.randint(1,10,size=10)
a

array([9, 3, 4, 2, 4, 9, 2, 6, 4, 4])

In [168]:
np.argmin(a)

3

In [169]:
np.max(a)

9

In [170]:
np.argmax(a)

0

In [171]:
a=np.random.random((32,1,28,28))
a.shape

(32, 1, 28, 28)

In [178]:
np.mean(a), np.std(a), np.min(a), np.max(a), np.median(a)

(0.4999903119045023,
 0.2898208161450737,
 4.099154093606394e-06,
 0.9999446128568541,
 0.497956537856095)

In [180]:
x_train_std=(x_trian-np.mean(a))/np.std(a)

NameError: name 'x_trian' is not defined

In [182]:
a=np.array([[1,2,3],
            [4,5,6]])

In [183]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [184]:
a.shape

(2, 3)

In [185]:
b=np.arange(1,7).reshape((2,3))
b.shape

(2, 3)

In [191]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [186]:
a+1

array([[2, 3, 4],
       [5, 6, 7]])

In [189]:
a+np.array([[1,2,3]])

array([[2, 4, 6],
       [5, 7, 9]])

In [190]:
a+b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [192]:
a+1

array([[2, 3, 4],
       [5, 6, 7]])

In [193]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [196]:
mask=a>5
mask

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [198]:
a[mask]

array([6, 7, 8, 9])

In [199]:
x_train=np.random.random((32,1,28,28))
y_label=np.random.randint(0,10,(32,1))
x_train.shape, y_label.shape

((32, 1, 28, 28), (32, 1))

In [204]:
mask=y_label==3
mask.flatten().shape

(32,)

In [206]:
mask = (y_label ==3) | (y_label==4)
mask.flatten().shape

(32,)

In [205]:
np.sum(mask)

2

In [203]:
y_label==3

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False]])

In [200]:
y_label

array([[6],
       [2],
       [2],
       [6],
       [5],
       [7],
       [8],
       [8],
       [4],
       [8],
       [9],
       [0],
       [0],
       [2],
       [3],
       [7],
       [5],
       [1],
       [9],
       [0],
       [7],
       [0],
       [8],
       [1],
       [7],
       [3],
       [0],
       [9],
       [9],
       [6],
       [7],
       [4]])

In [207]:
idx=[1,3,5]
a[idx]

array([1, 3, 5])

In [208]:
a= np.random.randint(0,10, size=10)
idx = np.argsort(a)
a, idx

(array([6, 6, 0, 5, 2, 0, 9, 1, 8, 4]),
 array([2, 5, 7, 4, 9, 3, 0, 1, 8, 6], dtype=int64))

In [209]:
a[idx[:5]]

array([0, 0, 1, 2, 4])