In [3]:
import numpy as np
import pandas as pd
rainfall = pd.read_csv('Notebooks_v1/data/Seattle2014.csv')['PRCP'].values
inches=rainfall/254

In [4]:
inches.shape

(365,)

In [5]:
%matplotlib 
import matplotlib.pyplot as plt
import seaborn; seaborn.set()
plt.hist(inches,40)

Using matplotlib backend: TkAgg


(array([245.,  14.,  13.,  17.,   8.,   6.,   5.,   6.,   4.,   3.,   7.,
          6.,   3.,   3.,   3.,   4.,   4.,   2.,   4.,   0.,   0.,   1.,
          1.,   1.,   0.,   0.,   0.,   2.,   1.,   1.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   1.]),
 array([0.        , 0.04596457, 0.09192913, 0.1378937 , 0.18385827,
        0.22982283, 0.2757874 , 0.32175197, 0.36771654, 0.4136811 ,
        0.45964567, 0.50561024, 0.5515748 , 0.59753937, 0.64350394,
        0.6894685 , 0.73543307, 0.78139764, 0.8273622 , 0.87332677,
        0.91929134, 0.96525591, 1.01122047, 1.05718504, 1.10314961,
        1.14911417, 1.19507874, 1.24104331, 1.28700787, 1.33297244,
        1.37893701, 1.42490157, 1.47086614, 1.51683071, 1.56279528,
        1.60875984, 1.65472441, 1.70068898, 1.74665354, 1.79261811,
        1.83858268]),
 <BarContainer object of 40 artists>)

In [6]:
x=np.array([1,2,3,4,5])

In [7]:
x<3

array([ True,  True, False, False, False])

In [8]:
x>3

array([False, False, False,  True,  True])

In [9]:
x<=3

array([ True,  True,  True, False, False])

In [10]:
x>=3

array([False, False,  True,  True,  True])

In [11]:
x!=3

array([ True,  True, False,  True,  True])

In [12]:
(2*x)==(x**2)

array([False,  True, False, False, False])

In [17]:
rng=np.random.RandomState(0)
x=rng.randint(10,size=(3,4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [18]:
x<6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [19]:
print(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [20]:
np.count_nonzero(x<6)

8

In [21]:
np.sum(x<6)

8

In [22]:
np.sum(x<6,axis=1)

array([4, 2, 2])

In [27]:
np.any(x>8)

True

In [28]:
np.any(x<0)

False

In [29]:
np.all(x<10)

True

In [30]:
np.all(x==6)

False

In [31]:
np.all(x<8,axis=1)

array([ True, False,  True])

In [33]:
np.sum((inches>0.5)&(inches<1))

29

In [39]:
inches>(0.5&inches)<1

TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [40]:
np.sum(~((inches<=0.5)|(inches>=1)))

29

In [41]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [42]:
x<5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [43]:
x[x<5]

array([0, 3, 3, 3, 2, 4])

In [44]:
rainy=(inches>0)

In [45]:
summer=(np.arange(365)-172<90)&(np.arange(365)-172>0)

In [50]:
np.median(inches[rainy])

0.19488188976377951

In [51]:
np.median(inches[summer])

0.0

In [52]:
np.max(inches[summer])

0.8503937007874016

In [55]:
np.median(inches[rainy&~summer])

0.20078740157480315

In [56]:
bool(42),bool(0)

(True, False)

In [57]:
bool(42 and 0)

False

In [58]:
bool(42 or 0)

True

In [59]:
bin(42)

'0b101010'

In [60]:
bin(59)

'0b111011'

In [61]:
bin(42&59)

'0b101010'

In [62]:
bin(42|59)

'0b111011'

In [65]:
A=np.array([1,0,1,0,1,0],dtype=bool)
B=np.array([1,1,1,0,1,1],dtype=bool)

In [66]:
A|B

array([ True,  True,  True, False,  True,  True])

In [67]:
x=np.arange(10)
(x>4)&(x<8)

array([False, False, False, False, False,  True,  True,  True, False,
       False])

In [3]:
import numpy as np
rand = np.random.RandomState(42)
x=rand.randint(100,size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [69]:
[x[3],x[7],x[2]]

[71, 86, 14]

In [70]:
ind=[3,7,4]

In [71]:
x[ind]

array([71, 86, 60])

In [13]:
import numpy as np
rand = np.random.RandomState(42)
x=rand.randint(100,size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [14]:
[x[3],x[7],x[2]]

[71, 86, 14]

In [15]:
ind=[3,7,4]
x[ind]

array([71, 86, 60])

In [16]:
ind=np.array([[3,7],[4,5]])

In [17]:
x[ind]

array([[71, 86],
       [60, 20]])

In [16]:
x=np.arange(12).reshape((3,4))

In [17]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
row=np.array([0,1,2])
col=np.array([2,1,3])
x[row,col]

array([ 2,  5, 11])

In [14]:
x[row[:,np.newaxis],col]

NameError: name 'row' is not defined

In [13]:
row[:,np.newaxis]*col

NameError: name 'row' is not defined

In [25]:
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [26]:
x[2,[2,0,1]]

array([10,  8,  9])

In [27]:
x[1:,[2,0,1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

In [19]:
mask=np.array([1,0,1,0],dtype=bool)
x[row[:,np.newaxis],mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [21]:
mask=np.array([1,0,1,0])
x[row[:,np.newaxis],mask]

array([[1, 0, 1, 0],
       [5, 4, 5, 4],
       [9, 8, 9, 8]])

In [30]:
mean=[0,0]
cov=[[1,2],
    [2,5]]
x=rand.multivariate_normal(mean,cov,100)
x.shape

(100, 2)

In [32]:
%matplotlib 
import matplotlib.pyplot as plt
import seaborn;seaborn.set()
plt.scatter(x[:,0],x[:,-1]);

Using matplotlib backend: TkAgg


In [35]:
indices = np.random.choice(x.shape[0],20,replace=False)
indices

array([11, 58, 96, 82, 23, 40, 47, 79, 98, 16, 24, 99, 97, 64, 80, 18,  6,
       32, 35, 20])

In [38]:
selection = x[indices]

selection.shape

(20, 2)

In [39]:
plt.scatter(x[:,0],x[:,1],alpha=0.3)
plt.scatter(selection[:,0],selection[:,1],
            facecolor='none',s=200)

In [40]:
x=np.arange(10)
i=np.array([2,1,8,4])
x[i]=99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


In [41]:
x[i]-=10
print(x)

[ 0 89 89  3 89  5  6  7 89  9]


In [42]:
x=np.zeros(10)
x[[0,0]]=[4,6]
print(x)

[6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [43]:
i=[2,3,3,4,4,4]
x[i]+=1
x

array([6., 0., 1., 1., 1., 0., 0., 0., 0., 0.])

In [45]:
i=[2,3,3,4,4,4]
x[i]+=1
x

array([6., 0., 3., 3., 3., 0., 0., 0., 0., 0.])

In [46]:
x=np.zeros(10)
np.add.at(x,i,1)
print(x)

[0. 0. 1. 2. 3. 0. 0. 0. 0. 0.]


In [47]:
np.random.seed(42)
x=np.random.randn(100)

In [50]:
bins=np.linspace(-5,5,20)
counts=np.zeros_like(bins)

In [51]:
i=np.searchsorted(bins,x)

In [52]:
np.add.at(counts,i,1)

In [58]:
import matplotlib.pyplot as plt
plt.plot(bins,counts,linestyle='steps');

ValueError: 'steps' is not a valid value for ls; supported values are '-', '--', '-.', ':', 'None', ' ', '', 'solid', 'dashed', 'dashdot', 'dotted'

In [67]:
pip install matplotlib

In [71]:
import matplotlib.pyplot
plt.hist(x,bins,histtye='step')

AttributeError: Rectangle.set() got an unexpected keyword argument 'histtye'

In [72]:
import matplotlib.pyplot as plt
plt.plot(bins,counts,linestyle='steps');

ValueError: 'steps' is not a valid value for ls; supported values are '-', '--', '-.', ':', 'None', ' ', '', 'solid', 'dashed', 'dashdot', 'dotted'

In [73]:
L=[3,1,4,1,5,9,2,6]
sorted(L)

[1, 1, 2, 3, 4, 5, 6, 9]

In [74]:
L.sort()
print(L)

[1, 1, 2, 3, 4, 5, 6, 9]


In [75]:
sorted('python')

['h', 'n', 'o', 'p', 't', 'y']

In [76]:
import numpy as np
x=np.array([2,1,4,3,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [77]:
x.sort()

In [78]:
print(x)

[1 2 3 4 5]


In [79]:
x=np.array([2,1,4,3,5])
i=np.argsort(x)
print(i)

[1 0 3 2 4]


In [80]:
x[i]

array([1, 2, 3, 4, 5])

In [81]:
rand=np.random.RandomState(42)

In [83]:
x=rand.randint(0,10,(4,6))
print(x)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [85]:
np.sort(x,axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [11]:
np.sort(x,axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [98]:
x=np.array([7,2,3,1,6,5,4])
np.partition(x,3)

array([2, 1, 3, 4, 6, 5, 7])

In [100]:
x=rand.randint(0,10,(4,6))
print(x)

np.partition(x,2,axis=1)

[[6 7 2 0 3 1]
 [7 3 1 5 5 9]
 [3 5 1 9 1 9]
 [3 7 6 8 7 4]]


array([[0, 1, 2, 6, 3, 7],
       [1, 3, 5, 7, 5, 9],
       [1, 1, 3, 9, 5, 9],
       [3, 4, 6, 8, 7, 7]])

In [101]:
x=rand.rand(10,2)

In [105]:
%matplotlib
import matplotlib.pyplot as plt
import seaborn;seaborn.set()
plt.scatter(x[:,0],x[:,1],s=100)

Using matplotlib backend: TkAgg


In [107]:
dist_sq=np.sum((x[:,np.newaxis,:]-x[np.newaxis,:,:])**2,axis=-1)

In [108]:
differences = x[:,np.newaxis,:]-x[np.newaxis,:,:]
differences.shape

(10, 10, 2)

In [110]:
sq_differences=differences **2
sq_differences.shape

(10, 10, 2)

In [111]:
dsit_sq=sq_differences.sum(-1)

In [112]:
dist_sq.shape

(10, 10)

In [114]:
dist_sq.diagonal()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [115]:
nearest=np.argsort(dist_sq,axis=1)

In [116]:
print(nearest)

[[0 9 2 5 8 1 7 3 6 4]
 [1 5 8 7 0 9 2 3 6 4]
 [2 0 3 6 9 7 4 1 5 8]
 [3 6 4 2 7 0 9 1 5 8]
 [4 6 3 2 7 0 9 1 5 8]
 [5 8 1 0 9 7 2 3 6 4]
 [6 3 4 2 0 7 9 1 5 8]
 [7 1 2 5 0 3 8 4 9 6]
 [8 5 1 9 0 7 2 3 6 4]
 [9 0 8 5 2 1 7 3 6 4]]


In [120]:
k=2
nearst_partition=np.argpartition(dist_sq,k+1,axis=1)

In [123]:
plt.scatter(x[:,0],x[:,1],s=100)
k=2
for i in range(x.shape[0]):
    for j in nearst_partition[i,:k+1]:
        plt.plot(*zip(x[j],x[i]),color='black')

In [1]:
import numpy as np

name=['Alice','Bob','Cathy','Doug']
age=[25,45,37,19]
weight=[55.0,85.5,68.0,61.5]

In [23]:
x=np.zeros(4,dtype=int)

In [14]:
data=np.zeros(4,dtype={'names':('name','age','weight'),
                        'formats':('U10','i4','f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [16]:
data['name']=name
data['age']=age
data['weight']=weight
print(data)

NameError: name 'name' is not defined

In [17]:
data['name']

array(['', '', '', ''], dtype='<U10')

In [18]:
data[0]

('', 0, 0.)

In [19]:
data[-1]['name']

''

In [20]:
data[data['age']<30]['name']

array(['', '', '', ''], dtype='<U10')

In [2]:
import numpy as np
np.dtype({'names':('name','age','weight'),
          'formats':('U10','i4','f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [3]:
np.dtype({'names':('name','age','weight'),
          'formats':((np.str_,10),int,np.float32)})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [5]:
np.dtype([('name','S10'),('age','i4'),('wiehgt','f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('wiehgt', '<f8')])

In [6]:
np.dtype('S10,i4,f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

In [8]:
tp=np.dtype([('id','i8'),('mat','f8',(3,3))])
x=np.zeros(1,dtype=tp)
print(x[0])
print(x['mat'][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
data['age']

array([0, 0, 0, 0])