In [1]:
a=5
type(a)

int

In [3]:
a=5.0
type(a)

float

In [4]:
l=list()
l.append(a)
l

[5.0]

In [6]:
l=list()
l.append(a)
l.append(max)

In [7]:
type(max)

builtin_function_or_method

In [10]:
l.append(max)
l.append(range)

In [12]:
l.append(numpy.array([[1,2],[3,4]])

SyntaxError: unexpected EOF while parsing (2161950269.py, line 1)

In [13]:
for item in l:
    print(item)

5.0
<built-in function max>
<built-in function max>
<class 'range'>
<built-in function max>
<class 'range'>


In [14]:
aa = 'hello'

for s in aa:
    print(s)
type(aa)

h
e
l
l
o


str

In [15]:
for i in range(10):
    print(i, sep=' ')

0
1
2
3
4
5
6
7
8
9


In [16]:
map(int,['1','2','3'])

In [17]:
for i in map(int, ['1','2','3']):
    print(i)

1
2
3


In [18]:
list(map(int,['1','2','3']))

[1, 2, 3]

In [19]:
import numpy as np

In [20]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [22]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [23]:
a

5.0

In [32]:
import numpy as np
a = np.array([1,2,3,4],dtype='int32')
a
a.dtype, a.shape

(dtype('int32'), (4,))

In [26]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [43]:
a=np.array([range(i,i+3) for i in [2,4,6]])
a

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [44]:
a.shape, a.dtype

((3, 3), dtype('int32'))

In [46]:
def np_info(a):
    print(type(a), a.shape, a.dtype)
np_info(a)

<class 'numpy.ndarray'> (3, 3) int32


In [51]:
b=np.ones((2,3),dtype=float)
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [52]:
np_info(b)

<class 'numpy.ndarray'> (2, 3) float64


In [55]:
a=np.zeros((32,1,28,28))
np_info(a)

<class 'numpy.ndarray'> (32, 1, 28, 28) float64


In [62]:
a= np.arange(10)
np_info(a)

<class 'numpy.ndarray'> (10,) int32


In [71]:
x=np.linspace(-1,1,100)
x

array([-1.        , -0.97979798, -0.95959596, -0.93939394, -0.91919192,
       -0.8989899 , -0.87878788, -0.85858586, -0.83838384, -0.81818182,
       -0.7979798 , -0.77777778, -0.75757576, -0.73737374, -0.71717172,
       -0.6969697 , -0.67676768, -0.65656566, -0.63636364, -0.61616162,
       -0.5959596 , -0.57575758, -0.55555556, -0.53535354, -0.51515152,
       -0.49494949, -0.47474747, -0.45454545, -0.43434343, -0.41414141,
       -0.39393939, -0.37373737, -0.35353535, -0.33333333, -0.31313131,
       -0.29292929, -0.27272727, -0.25252525, -0.23232323, -0.21212121,
       -0.19191919, -0.17171717, -0.15151515, -0.13131313, -0.11111111,
       -0.09090909, -0.07070707, -0.05050505, -0.03030303, -0.01010101,
        0.01010101,  0.03030303,  0.05050505,  0.07070707,  0.09090909,
        0.11111111,  0.13131313,  0.15151515,  0.17171717,  0.19191919,
        0.21212121,  0.23232323,  0.25252525,  0.27272727,  0.29292929,
        0.31313131,  0.33333333,  0.35353535,  0.37373737,  0.39

In [78]:
y=f(x)
fig.plot(x,y)

NameError: name 'f' is not defined

In [80]:
x_train=np.random.random((32,1,28,28))
x_train
np_info(x_train)

<class 'numpy.ndarray'> (32, 1, 28, 28) float64


In [97]:
a=np.random.normal(50, 2.0, (24,))
np_info(a)

<class 'numpy.ndarray'> (24,) float64


In [84]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the `~numpy.random.Generator.normal`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
     

In [85]:
help(np.random.random)

Help on built-in function random:

random(...) method of numpy.random.mtrand.RandomState instance
    random(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.



In [90]:
import numpy as np
np.random.seed(0)

x1=np.random.randint(10,size=6)
x1

array([5, 0, 3, 3, 7, 9])

In [92]:
x2=np.random.randint(10,size=(3,4))
x3=np.random.randint(10,size=(3,4,5))

In [88]:
import matplotlib.pyplot as plt 

plt.plot(range(len(a)),a.flattern())

AttributeError: 'numpy.ndarray' object has no attribute 'flattern'

In [94]:
x2

array([[8, 1, 5, 9],
       [8, 9, 4, 3],
       [0, 3, 5, 0]])

In [95]:
x3

array([[[2, 3, 8, 1, 3],
        [3, 3, 7, 0, 1],
        [9, 9, 0, 4, 7],
        [3, 2, 7, 2, 0]],

       [[0, 4, 5, 5, 6],
        [8, 4, 1, 4, 9],
        [8, 1, 1, 7, 9],
        [9, 3, 6, 7, 2]],

       [[0, 3, 5, 9, 4],
        [4, 6, 4, 4, 3],
        [4, 4, 8, 4, 3],
        [7, 5, 5, 0, 1]]])

In [99]:
import numpy as np 

def np_info(a):
    print(f'type: {type(a)}, shape:{a.shape}, dim:{a.nim}, size={a.size}, dtype:{d.dtype})

a=np.array([[1,2,3],
            [4,5,6]])
np_info(a)


SyntaxError: EOL while scanning string literal (1465667855.py, line 4)

In [100]:
np.max(a)

53.96742160207221