In [1]:
import numpy as np

ar1=np.array([1,2,3,4,5])
ar2=np.array([[1,2,3],[4,5,6]])
print(ar1)
print(ar2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [2]:
import numpy as np

ar3 = np.random.randn(3)
ar4 = np.random.randn(2,3)

print(ar3)
print(ar4)

[ 2.21636652 -1.15772687  1.7702087 ]
[[-0.29304736  0.0482903   0.40176336]
 [ 0.65847483  0.14115883  0.4669077 ]]


In [3]:
import numpy as np

ar5=np.zeros(5)
ar6=np.ones((2,3))
print(ar5)
print(ar6)

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
import numpy as np
ar7 = np.arange(20,200,10)
ar7

array([ 20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130, 140,
       150, 160, 170, 180, 190])

In [7]:
ar8=ar7.reshape(3,6)
ar8

array([[ 20,  30,  40,  50,  60,  70],
       [ 80,  90, 100, 110, 120, 130],
       [140, 150, 160, 170, 180, 190]])

In [9]:
import numpy as np
ar1=np.arange(1,21,1)
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [10]:
ar1[1]

2

In [11]:
ar2=ar1.reshape(2,10)
ar2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [12]:
ar2[1][1]=100

In [13]:
ar2

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11, 100,  13,  14,  15,  16,  17,  18,  19,  20]])

In [14]:
ar2[1][0], ar2[1][1], ar2[1][2]

(11, 100, 13)

In [15]:
ar1=np.arange(1,11,1)

In [16]:
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
ar2=ar1+3

In [18]:
ar2

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [19]:
ar3=ar1*2

In [20]:
ar3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [22]:
print(ar2,"\n",ar3)

[ 4  5  6  7  8  9 10 11 12 13] 
 [ 2  4  6  8 10 12 14 16 18 20]


In [23]:
ar1=np.array([[5,7,9],[-7,-6,19],[6,9,11]])

In [24]:
ar1

array([[ 5,  7,  9],
       [-7, -6, 19],
       [ 6,  9, 11]])

In [25]:
ar1.sum()

53

In [26]:
ar1.mean()

5.888888888888889

In [27]:
ar1.max()

19

In [28]:
ar1.min()

-7

In [29]:
ar1.max(axis=0)

array([ 6,  9, 19])

In [30]:
ar1.max(axis=1)

array([ 9, 19, 11])

In [31]:
ar1=np.array([[5,7,9],[-7,-6,19],[6,9,11]])

In [32]:
ar1>0

array([[ True,  True,  True],
       [False, False,  True],
       [ True,  True,  True]])

In [33]:
m_count=(ar1<0).sum()
m_count

2

In [34]:
ar2=np.where(ar1<0,0,ar1)

In [35]:
ar2

array([[ 5,  7,  9],
       [ 0,  0, 19],
       [ 6,  9, 11]])

In [36]:
ar1=np.array([[5,7,9],[-3,-6,19],[6,4,11]])

In [37]:
ar1

array([[ 5,  7,  9],
       [-3, -6, 19],
       [ 6,  4, 11]])

In [39]:
ar1.sort(0)
ar1

array([[-3, -6,  9],
       [ 5,  4, 11],
       [ 6,  7, 19]])

In [40]:
ar1.sort(1)
ar1

array([[-6, -3,  9],
       [ 4,  5, 11],
       [ 6,  7, 19]])

In [41]:
import pandas as pd

sr1=pd.Series([10,30,20,40,60])
print(sr1)

0    10
1    30
2    20
3    40
4    60
dtype: int64


In [44]:
sr1 = pd.Series([10,30,20,40,60])
sr1.values

array([10, 30, 20, 40, 60], dtype=int64)

In [45]:
sr1.index

RangeIndex(start=0, stop=5, step=1)

In [43]:
sr1[2]

20

In [46]:
sr1=pd.Series([10,30,20,40,60], index=['a','b','c','d','e'])

In [48]:
sr1

a    10
b    30
c    20
d    40
e    60
dtype: int64

In [50]:
sr1[1]

C:\Users\user\AppData\Local\Temp\ipykernel_17132\2515317115.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sr1[1]


30

In [51]:
sr1['b']

30

In [53]:
sr1=pd.Series([10,30,20,40,60], index=['a','b','c','d','e'])

In [54]:
sr1

a    10
b    30
c    20
d    40
e    60
dtype: int64

In [55]:
sr1[[1,2]]

C:\Users\user\AppData\Local\Temp\ipykernel_17132\2247156471.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sr1[[1,2]]


b    30
c    20
dtype: int64

In [56]:
sr1[['a','c']]

a    10
c    20
dtype: int64

In [57]:
sr1=pd.Series([10,30,20,40,60], index=['a','b','c','d','e'])
sr1[1:4]

b    30
c    20
d    40
dtype: int64

In [58]:
sr1['b':'d']

b    30
c    20
d    40
dtype: int64

In [60]:
import pandas as pd

df1 = pd.DataFrame([[10,20,30],[40,50,60]])
df1

0   1   2
0  10  20  30
1  40  50  60

In [61]:
dic1 = {'fruit':['사과','배','감','귤','바나나'],
        'price':[100,200,150,50,200],
        'qty':[10,25,30,20,15]}
df1 = pd.DataFrame(dic1)
df1

fruit  price  qty
0    사과    100   10
1     배    200   25
2     감    150   30
3     귤     50   20
4   바나나    200   15

In [64]:
df1=pd.DataFrame(dic1,index=['a','b','c','d','e'])
df1

fruit  price  qty
a    사과    100   10
b     배    200   25
c     감    150   30
d     귤     50   20
e   바나나    200   15

In [65]:
df1.rename(columns={'fruit':'과일', 'price':'가격', 'qty':'수량'},inplace=True)
df1.rename(index={'a':'01','b':'02','c':'03','d':'04','e':'05'},inplace=True)
df1

과일   가격  수량
01   사과  100  10
02    배  200  25
03    감  150  30
04    귤   50  20
05  바나나  200  15

In [67]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv("https://raw.githubserconnet.com/datasciencedojo/datasets/master/titanic.csv")

URLError: <urlopen error [Errno 11001] getaddrinfo failed>